### PR TITLE
add default export

### PR DESCRIPTION
**Pull request by zixia**
Enable us to use `import encoding from 'encoding-down'` by adding `default` export.

### CODE REVIEW

**Comment by kesla** [comment]
@zixia Have you tried running this? It just doesn't look right to me, since there is no `default` property on the `DB` object it should simply export `undefined`.

**Comment by zixia** [comment]
I use this pattern a lot because:

`module.exports = DB.default = DB`

equals to

```js
DB.default = DB
module.exports = DB
```

Then we will have a `default` property on the DB object.

**Comment by ralphtheninja** [comment]
2.3.0

**Comment by kesla** [comment]
@zixia oops, sorry for my quick comment. Yeah you're correct, I didn't read the code correctly

**Comment by zixia** [comment]
@kesla no problem, I also feel it's not right when I saw this pattern the first time. But it's really convenient to use.

I need to get the `default` export to make `rollup` tool happy. Looking forward to also have this on `levelup` and `leveldown` module. 

Cheers!

**Pull request merged**
