### PR TITLE
Drop 0.12

### LINKED ISSUE #24: Drop 0.12
- [x] Remove 0.12 from travis
- [x] Add node version badge

Should we bump major here too? @juliangruber @ralphtheninja

### PR DESCRIPTION
**Pull request by vweevers**
Closes #24.

### CODE REVIEW

**Comment by vweevers** [comment]
@juliangruber major or patch? It was kinda implied that we didn't support 0.12 here.

**Comment by juliangruber** [comment]
> It was kinda implied that we didn't support 0.12 here.

how so?

**Comment by vweevers** [comment]
Because we introduced it as part of level@2.

**Comment by vweevers** [comment]
Nevermind, that's the wrong way to think about this. Just looking at `encoding-down` by itself, it drops a node version, so it's major.

**Comment by vweevers** [comment]
3.0.0 (sorry for the delay, busy work week)

**Pull request merged**
